[package]
name = "tex-parser"
version = "0.1.0"
authors = ["Richard MÃ¶rbitz <richard.moerbitz@tu-dresden.de>"]
edition = "2018"

[dependencies]
num = "0.2"
gen-iter = { git = "https://github.com/sumeet/gen-iter" }
